# ----------------------------
# Makefile Options
# ----------------------------

NAME = DEMO
ICON = icon.png
DESCRIPTION = "Cedar Demo"
COMPRESSED = NO
ARCHIVED = NO

EXTRA_ASM_SOURCES = $(wildcard ../out/*)

CFLAGS = -Wall -Wextra -Oz -I ../include/
CXXFLAGS = -Wall -Wextra -Oz -I ../include/

# ----------------------------

include $(shell cedev-config --makefile)