
# ----------------------------
# Makefile Options
# ----------------------------

NAME = DEMO
ICON = icon.png
DESCRIPTION = "Cedar Demo"
COMPRESSED = NO
ARCHIVED = NO

EXTRA_ASM_SOURCES = ../../out/libcedar.src

CFLAGS = -Wall -Wextra -Oz -I ../../include/
CXXFLAGS = -Wall -Wextra -Oz -I ../../include/

# ----------------------------

include $(shell cedev-config --makefile)